"""create initial tables

Revision ID: 083cd060d880
Revises:
Create Date: 2026-10-08 13:03:32.717826

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "083cd060d880"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "books",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("isbn", sa.Text(), nullable=True),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("author", sa.Text(), nullable=True),
        sa.Column("publisher", sa.Text(), nullable=True),
        sa.Column("published_date", sa.Text(), nullable=True),
        sa.Column("list_price", sa.Integer(), nullable=True),
        sa.Column("cover_image_url", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "list_price >= 0", name=op.f("ck_books_list_price_non_negative")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_books")),
        sa.UniqueConstraint("isbn", name=op.f("uq_books_isbn")),
        sqlite_autoincrement=True,
    )
    op.create_table(
        "purchases",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("book_id", sa.Integer(), nullable=False),
        sa.Column("purchased_on", sa.Date(), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("store", sa.Text(), nullable=True),
        sa.Column("memo", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "amount >= 0", name=op.f("ck_purchases_amount_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["book_id"],
            ["books.id"],
            name=op.f("fk_purchases_book_id_books"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_purchases")),
        sqlite_autoincrement=True,
    )
    with op.batch_alter_table("purchases", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_purchases_book_id"), ["book_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_purchases_purchased_on"), ["purchased_on"], unique=False
        )

    op.create_table(
        "reading_records",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("book_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("started_at", sa.Date(), nullable=True),
        sa.Column("finished_at", sa.Date(), nullable=True),
        sa.Column("memo", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "status IN ('unread', 'reading', 'finished')",
            name=op.f("ck_reading_records_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["book_id"], ["books.id"], name=op.f("fk_reading_records_book_id_books")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reading_records")),
        sa.UniqueConstraint("book_id", name=op.f("uq_reading_records_book_id")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("reading_records")
    with op.batch_alter_table("purchases", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_purchases_purchased_on"))
        batch_op.drop_index(batch_op.f("ix_purchases_book_id"))

    op.drop_table("purchases")
    op.drop_table("books")
    # ### end Alembic commands ###
