"""cascade book deletes and add disposed_on

Revision ID: e07278ae3709
Revises: 083cd060d880
Create Date: 2026-10-10 12:17:39.346978

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e07278ae3709"
down_revision: str | Sequence[str] | None = "083cd060d880"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("books", schema=None) as batch_op:
        batch_op.add_column(sa.Column("disposed_on", sa.Date(), nullable=True))

    with op.batch_alter_table("purchases", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_purchases_book_id_books"), type_="foreignkey"
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_purchases_book_id_books"),
            "books",
            ["book_id"],
            ["id"],
            ondelete="CASCADE",
        )

    with op.batch_alter_table("reading_records", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_reading_records_book_id_books"), type_="foreignkey"
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_reading_records_book_id_books"),
            "books",
            ["book_id"],
            ["id"],
            ondelete="CASCADE",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("reading_records", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_reading_records_book_id_books"), type_="foreignkey"
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_reading_records_book_id_books"), "books", ["book_id"], ["id"]
        )

    with op.batch_alter_table("purchases", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_purchases_book_id_books"), type_="foreignkey"
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_purchases_book_id_books"),
            "books",
            ["book_id"],
            ["id"],
            ondelete="RESTRICT",
        )

    with op.batch_alter_table("books", schema=None) as batch_op:
        batch_op.drop_column("disposed_on")

    # ### end Alembic commands ###
